-- 1. 춘 기술대학교의 학과 이름과 계열을 표시하기,
-- 단, 출력 헤더는 '학과명', '계열'로 표시한다.

SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원을 '@@과의 정원은 00명 입니다.'과 같은 형태로 출력

SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. "국어국문학과"에 다니는 여학생 중 현재 휴학중인 여학생을 찾아 출력

SELECT STUDENT_NAME AS 학생이름
FROM TB_DEPARTMENT JOIN TB_STUDENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '001' AND SUBSTR(STUDENT_SSN, 8, 1) = '2' AND ABSENCE_YN = 'Y';

-- 4. 도서관에서 대출 장기 연체자들을 찾아 이름을 출력
-- 대상자 학번 : A513079 | A513090 | A513091 | A513110 | A513119

SELECT STUDENT_NAME AS 학생이름
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079',  'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학정원이 20명 이상 30명 이하인 학과들의 학과 이름과 계열을 출력

SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 춘 대학교는 총장을 제외하고 모든 교수들이 소속 학과를 가진다. 총장의 이름을 출력

SELECT PROFESSOR_NAME AS 총장
FROM TB_DEPARTMENT RIGHT JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO IS NULL;

-- 7. 전산상의 착오로 학과가 지정되지 않은 학생이 있는지 출력

SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO = ' ' OR DEPARTMENT_NO IS NULL;

-- 8. 수강신청, 선수과목을 확인해야 하는데, 선수과목이 어떤 과목인지 조회

SELECT CLASS_NO AS 선수과목
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 춘 대학에는 어떤 계열들이 있는지 조회

SELECT CATEGORY AS 계열
FROM TB_DEPARTMENT
GROUP BY CATEGORY;

-- 10. 02학번 전주에 거주하는 학생들의 학번, 이름, 주민번호를 출력(단, 휴학한 사람 제외)

SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, STUDENT_SSN AS 주민번호
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND STUDENT_NO LIKE 'A2%' AND ABSENCE_YN = 'N';