<<<<<<< HEAD
SELECT * FROM    ALL_CONSTRAINTS
WHERE    TABLE_NAME = 'TB_CATEGORY';

-- 1. °è¿­ Á¤º¸¸¦ ÀúÀåÇÒ Ä«Å×°í¸® Å×ÀÌºí ¸¸µé±â
-- USE_YNÀÇ ±âº»°ªÀº 'Y'·Î ¼³Á¤

CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. °ú¸ñ ±¸ºÐÀ» ÀúÀåÇÒ Å×ÀÌºí ¸¸µé±â
-- NO¿¡ PRIMARY KEY ¼³Á¤

CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3. TB_CATEGORY Å×ÀÌºíÀÇ NAME ÄÃ·³¿¡ PRIMARY_KEY »ý¼º

ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_NAME PRIMARY KEY(NAME);

-- 4. TB_CLASS_TYPE Å×ÀÌºíÀÇ NAME ÄÃ·³¿¡ NULL°ªÀÌ µé¾î°¡Áö ¾Êµµ·Ï ¼Ó¼º º¯°æ

ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5. µÎ Å×ÀÌºí¿¡¼­ ÄÃ·³¸íÀÌ NOÀÎ °ÍÀº ±âÁ¸ Å¸ÀÔÀ» À¯ÁöÇÏ¸é¼­ Å©±â´Â 10À¸·Î
-- ÄÃ·³¸íÀÌ NAMEÀÎ °ÍÀº ±âÁ¸ Å¸ÀÔÀ» À¯ÁöÇÏ¸é¼­ Å©±â 20À¸·Î º¯°æ

ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CALSS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

-- 6. µÎ Å×ÀÌºíÀÇ NO ÄÃ·³°ú NAME ÄÃ·³ÀÇ ÀÌ¸§À» °¢°¢ TB_¸¦ Á¦¿ÜÇÑ Å×ÀÌºí ÀÌ¸§ÀÌ ¾Õ¿¡ ºÙÀº ÇüÅÂ·Î º¯°æ

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN USE_YN TO CATEGORY_USE_YN;

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

-- 7. TB_CATEGORY Å×ÀÌºí°ú TB_CLASS_TYPE Å×ÀÌºíÀÇ PRIMARY KEY ÀÌ¸§À» º¯°æ

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT PK_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007638 TO PK_CLASS_NO;

-- 8. INSERT¹®À» ¼öÇà

INSERT INTO TB_CATEGORY VALUES ('°øÇÐ', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ÀÚ¿¬°úÇÐ', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ÀÇÇÐ', 'Y');
INSERT INTO TB_CATEGORY VALUES ('¿¹Ã¼´É', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ÀÎ¹®»çÈ¸', 'Y');
COMMIT;

-- 9. TB_DEPARTMENTÀÇ CATEGORY ÄÃ·³ÀÌ TB_CATEGORY Å×ÀÌºíÀÇ CATEGORY_NAME ÄÃ·³À» ºÎ¸ð°ªÀ¸·Î ÂüÁ¶ÇÏµµ·Ï
-- FOREIGN KEY¸¦ ÁöÁ¤, ÀÌ ¶§ KEY ÀÌ¸§Àº 'FK_Å×ÀÌºí¸í_ÄÃ·³¸í'À¸·Î ÁöÁ¤

ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY_NAME
FOREIGN KEY (CATEGORY)
REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- 10. ÇÐ»ý Á¤º¸°¡ ÀúÀåµÈ ÇÐ»ýÀÏ¹ÝÁ¤º¸VIEW ¸¸µé±â

CREATE OR REPLACE VIEW VW_ÇÐ»ýÀÏ¹ÝÁ¤º¸
        AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
            FROM TB_STUDENT;
=======
SELECT * FROM    ALL_CONSTRAINTS
WHERE    TABLE_NAME = 'TB_CATEGORY';

-- 1. ê³„ì—´ ì •ë³´ë¥¼ ì €ìž¥í•  ì¹´í…Œê³ ë¦¬ í…Œì´ë¸” ë§Œë“¤ê¸°
-- USE_YNì˜ ê¸°ë³¸ê°’ì€ 'Y'ë¡œ ì„¤ì •

CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. ê³¼ëª© êµ¬ë¶„ì„ ì €ìž¥í•  í…Œì´ë¸” ë§Œë“¤ê¸°
-- NOì— PRIMARY KEY ì„¤ì •

CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3. TB_CATEGORY í…Œì´ë¸”ì˜ NAME ì»¬ëŸ¼ì— PRIMARY_KEY ìƒì„±

ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_NAME PRIMARY KEY(NAME);

-- 4. TB_CLASS_TYPE í…Œì´ë¸”ì˜ NAME ì»¬ëŸ¼ì— NULLê°’ì´ ë“¤ì–´ê°€ì§€ ì•Šë„ë¡ ì†ì„± ë³€ê²½

ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5. ë‘ í…Œì´ë¸”ì—ì„œ ì»¬ëŸ¼ëª…ì´ NOì¸ ê²ƒì€ ê¸°ì¡´ íƒ€ìž…ì„ ìœ ì§€í•˜ë©´ì„œ í¬ê¸°ëŠ” 10ìœ¼ë¡œ
-- ì»¬ëŸ¼ëª…ì´ NAMEì¸ ê²ƒì€ ê¸°ì¡´ íƒ€ìž…ì„ ìœ ì§€í•˜ë©´ì„œ í¬ê¸° 20ìœ¼ë¡œ ë³€ê²½

ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CALSS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

-- 6. ë‘ í…Œì´ë¸”ì˜ NO ì»¬ëŸ¼ê³¼ NAME ì»¬ëŸ¼ì˜ ì´ë¦„ì„ ê°ê° TB_ë¥¼ ì œì™¸í•œ í…Œì´ë¸” ì´ë¦„ì´ ì•žì— ë¶™ì€ í˜•íƒœë¡œ ë³€ê²½

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN USE_YN TO CATEGORY_USE_YN;

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

-- 7. TB_CATEGORY í…Œì´ë¸”ê³¼ TB_CLASS_TYPE í…Œì´ë¸”ì˜ PRIMARY KEY ì´ë¦„ì„ ë³€ê²½

ALTER TABLE TB_CATEGORY RENAME CONSTRAINT PK_NAME TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007638 TO PK_CLASS_NO;

-- 8. INSERTë¬¸ì„ ìˆ˜í–‰

INSERT INTO TB_CATEGORY VALUES ('ê³µí•™', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ìžì—°ê³¼í•™', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ì˜í•™', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ì˜ˆì²´ëŠ¥', 'Y');
INSERT INTO TB_CATEGORY VALUES ('ì¸ë¬¸ì‚¬íšŒ', 'Y');
COMMIT;

-- 9. TB_DEPARTMENTì˜ CATEGORY ì»¬ëŸ¼ì´ TB_CATEGORY í…Œì´ë¸”ì˜ CATEGORY_NAME ì»¬ëŸ¼ì„ ë¶€ëª¨ê°’ìœ¼ë¡œ ì°¸ì¡°í•˜ë„ë¡
-- FOREIGN KEYë¥¼ ì§€ì •, ì´ ë•Œ KEY ì´ë¦„ì€ 'FK_í…Œì´ë¸”ëª…_ì»¬ëŸ¼ëª…'ìœ¼ë¡œ ì§€ì •

ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY_NAME
FOREIGN KEY (CATEGORY)
REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- 10. í•™ìƒ ì •ë³´ê°€ ì €ìž¥ëœ í•™ìƒì¼ë°˜ì •ë³´VIEW ë§Œë“¤ê¸°

CREATE OR REPLACE VIEW VW_í•™ìƒì¼ë°˜ì •ë³´
        AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
            FROM TB_STUDENT;
>>>>>>> e78bdca9e915ab8a583acb402425f0b4af0692c9
